def process_table(scraped):
        clean_scraped = list()

        i = 0
        while(i < len(scraped)):
            element = scraped[i].strip()
            if element not in ["", "Frage:", "Antwort:", "Erklärung:"]:
                result = element + " "
                while(i+1 < len(scraped) and element != ""):
                    i += 1
                    element = scraped[i].strip()
                    result += element + " "
                clean_scraped.append(result)
            elif element in ["Frage:", "Antwort:", "Erklärung:"]:
                clean_scraped.append(element)
            i += 1

        questions = list()
        answers = list()
        explanations = list()
        i = 0
        while(i+1 < len(clean_scraped)):
            element = clean_scraped[i]
            print(element)
            if element.strip() == "":
                i += 1
                continue
            elif "Frage:" in clean_scraped[i]:
                questions.append(clean_scraped[i+1].strip())
                i += 2
            elif "Antwort:" in clean_scraped[i]:
                answers.append(clean_scraped[i+1].strip())
                i += 2
            elif "Erklärung:" in clean_scraped[i]:
                explanations.append(clean_scraped[i+1].strip())
                i += 2
            else:
                i += 1

        return questions, answers, explanations
    
def process(scraped):
    result = ""
    for element in scraped:
        result += element.strip()
        result += " "
    return result

def process_table2(scraped):
        clean_scraped = list()
        for element in scraped:
            if element.strip() != "":
                clean_scraped.append(element)
        
        questions = list()
        answer_numbers = list()
        answers = list()
        explanations = list()
        i = 0
        while(i+1 < len(clean_scraped)):
            element = clean_scraped[i]
            if "Frage:" in clean_scraped[i]:
                if i+2 < len(clean_scraped):
                    if clean_scraped[i+2].strip().isnumeric():
                        questions.append(clean_scraped[i+1].strip())
                        answer_numbers.append(int(clean_scraped[i+2].strip()))
                        i += 3
                    elif "Antwort:" not in clean_scraped[i+1].strip():
                        questions.append(clean_scraped[i+1].strip())
                        answers.append(clean_scraped[i+2].strip())
                        i += 3
                    
            elif "Erklärung:" in clean_scraped[i]:
                explanations.append(clean_scraped[i+1].strip())
                i += 2
            i += 1
        
        answer_values = ['0', 'Ja, möglicherweise',
                    'Ja, wahrscheinlich',
                    'Ja',
                    'Ja, möglicherweise ein bisschen',
                    'Ja, wahrscheinlich ein bisschen',
                    'Ja, ein bisschen',
                    '7',
                    'Nein, möglicherweise nicht',
                    'Nein, wahrscheinlich nicht',
                    'Nein',
                    'Wissenschaftliche Belege fehlen']
        if len(answers) == 0:
            answers = [answer_values[num] for num in answer_numbers]

        return questions, answers, explanations

def process_table3(scraped):
    clean_scraped = list()

    i = 0
    while(i < len(scraped)):
        element = scraped[i].strip()
        if element not in ["", "Frage:", "Antwort:", "Beweislage:"]:
            result = element + " "
            while(i+1 < len(scraped) and element != ""):
                i += 1
                element = scraped[i].strip()
                result += element + " "
            clean_scraped.append(result)
        elif element in ["Frage:", "Antwort:", "Beweislage:"]:
            clean_scraped.append(element)
        i += 1
    
    questions = list()
    answers = list()
    explanations = list()
    i = 0
    while(i+1 < len(clean_scraped)):
        element = clean_scraped[i]
        print(element)
        if element.strip() == "":
            i += 1
            continue
        elif "Frage:" in clean_scraped[i]:
            questions.append(clean_scraped[i+1].strip())
            i += 2
        elif "Beweislage:" in clean_scraped[i]:
            if i+2 < len(clean_scraped) and clean_scraped[i+2].strip() != "":
                final = clean_scraped[i+1].strip() + " | " + clean_scraped[i+2].strip()
            else: 
                final = clean_scraped[i+1].strip() 
            answers.append(final)
            i += 3
        elif "Antwort:" in clean_scraped[i]:
            explanations.append(clean_scraped[i+1].strip())
            i += 2
        else:
            i += 1

    return questions, answers, explanations


table =  ['\n',
           '\n',
           '\n',
           'Frage:',
           '\n',
           'Senkt die Einnahme von Magnesiumsalzen die Häufigkeit und '
           'Intensität von Muskelkrämpfen ',
           'mit unbekannter Ursache?',
           '\n',
           '\n',
           '\n',
           '\n',
           'Antwort:',
           '\n',
           '\n',
           'wahrscheinlich\xa0',
           'Nein',
           '\n',
           '\n',
           '\n',
           '\xa0',
           '\n',
           '\n',
           '\n',
           'Frage:',
           '\n',
           'Senkt die Einnahme von Magnesiumsalzen die Häufigkeit und '
           'Intensität von anstrengungsbedingten Muskelkrämpfen ',
           'beim Sport?',
           '\n',
           '\n',
           '\n',
           '\n',
           'Antwort:',
           '\n',
           '\n',
           'wissenschaftliche Belege fehlen',
           '\n',
           '\n',
           '\n',
           '\xa0',
           '\n',
           '\n',
           '\n',
           'Frage:',
           '\n',
           'Senkt die Einnahme von Magnesiumsalzen die Häufigkeit und '
           'Intensität von Muskelkrämpfen ',
           'in der Schwangerschaft?',
           '\n',
           '\n',
           '\n',
           '\n',
           'Antwort:',
           '\n',
           '\n',
           'möglicherweise\xa0',
           'Ja',
           '\n',
           '\n',
           '\n',
           'Erklärung:',
           '\n',
           'Zur Wirksamkeit von Magnesiumsalzen bei anstrengungsbedingten '
           'Muskelkrämpfen, etwa bei Sportlern, finden sich keine qualitativ '
           'hochwertigen Studien. Bei Krämpfen der Beinmuskeln ohne erkennbare '
           'Ursache haben Forscher in Studien keinen Effekt von Magnesium '
           'nachweisen können, der über Placebo hinausgeht. Schwangere Frauen '
           'profitieren möglicherweise von Magnesiumpräparaten, allerdings '
           'sind diese Belege nicht sehr belastbar.\n',
           '\n',
           '\n',
           '\n']

table5 = ['\n',
 '\n',
 '\n',
 'Zeitungsartikel: ',
 '\n',
 'Luftverschmutzung erhöht Autismusrisiko',
 ' (18.6.2013, diePresse.com),',
 '\n',
 'Luftverschmutzung erhöht Autismus-Risiko für Kinder',
 ' (18.6.2013, derStandard.at),',
 '\n',
 'Luftverschmutzung erhöht Autismus-Risiko für Kinder',
 ' (19.6.2013, Krone.at),\n',
 '\n',
 '\n',
 '\n',
 'Frage:',
 '\n',
 'Vergrößert hohe Luftverschmutzung das Risiko für das Ungeborene, später Autismus zu entwickeln?',
 '\n',
 '\n',
 '\n',
 'Antwort:',
 '\n',
 'Möglicherweise gibt es einen Zusammenhang zwischen dem vermehrten Auftreten von Autismus und der Luftverschmutzung während der Schwangerschaft. Bisherige Studien wurden jedoch zu ungenau durchgeführt, um tatsächlich Luftverschmutzung als Ursache für Autismus zu identifizieren. Das mögliche Risiko sollte durch genauere Studien abgeklärt werden.',
 '\n',
 '\n',
 '\n',
 'Beweislage:',
 '\n',
 '\n',
 '\n',
 '\n',
 '\n',
 '\n',
 'Unzureichende',
 ' wissenschaftliche Beweislage',
 '\n',
 '\n',
 '\n',
 '\n']

table2 = ['\r\n        ',
        '\r\n        ',
        '\r\n            ',
        '\r\n                ',
        'Frage: ',
        '\r\n                ',
        'Kann Mönchspfeffer PMS-Beschwerden reduzieren? PMS ist die Abkürzung für das Prämenstruelle Syndrom. Damit sind Beschwerden gemeint, die in den Tagen vor der Menstruation auftreten.',
        '\r\n            ',
        '\r\n            ',
        '\r\n\r\n            ',
        '1',
        '\r\n\r\n            ',
        '\r\n                ',
        '\r\n                    ',
        'Antwort:',
        '\r\n                    ',
        '\r\n                        ',
        ' Ja,\r\n                        möglicherweise',
        '\r\n                ',
        '\r\n            ',
        '\r\n            ',
        '\r\n\r\n            ',
        '\r\n                ',
        '\r\n                    ',
        'Antwort:',
        '\r\n                   ',
        '\r\n                        ',
        ' Ja, wahrscheinlich',
        '\r\n                    ',
        '\r\n                ',
        '\r\n            ',
        '\r\n             \r\n\r\n            ',
        '\r\n                ',
        '\r\n                    ',
        'Antwort:',
        '\r\n                    ',
        '\r\n                        ',
        ' Ja',
        '\r\n                ',
        '\r\n            ',
        '\r\n             \r\n\r\n\r\n            ',
        '\r\n                ',
        '\r\n                    ',
        'Antwort:',
        '\r\n                    ',
        '\r\n                        ',
        ' Ja, möglicherweise\r\n                        ein bisschen',
        '\r\n                ',
        '\r\n            ',
        '\r\n             \r\n\r\n\r\n            ',
        '\r\n                ',
        '\r\n                    ',
        'Antwort:',
        '\r\n                     ',
        '\r\n                        ',
        ' Ja, wahrscheinlich\r\n                        ein bisschen',
        '\r\n                ',
        '\r\n            ',
        '\r\n             \r\n\r\n\r\n            ',
        '\r\n                ',
        '\r\n                    ',
        'Antwort:',
        '\r\n                     ',
        '\r\n                        ',
        ' Ja, ein bisschen',
        '\r\n                    ',
        '\r\n                ',
        '\r\n            ',
        '         \r\n             \r\n            ',
        '\r\n                ',
        '\r\n                    ',
        'Antwort:',
        '\r\n                    ',
        '\r\n                        ',
        ' Nein,\r\n                        möglicherweise nicht',
        '\r\n                ',
        '\r\n            ',
        '\r\n             \r\n\r\n            ',
        '\r\n                ',
        '\r\n                    ',
        'Antwort: ',
        '\r\n                    ',
        ' Nein,\r\n                        wahrscheinlich nicht',
        '\r\n                ',
        '\r\n            ',
        '\r\n             \r\n\r\n            ',
        '\r\n                ',
        '\r\n                    ',
        'Antwort:',
        '\r\n                    ',
        ' Nein',
        '\r\n                ',
        '\r\n            ',
        '\r\n\r\n\t\t\t',
        '\r\n                ',
        '\r\n                    ',
        'Antwort:',
        '\r\n                    ',
        'Wissenschaftliche Belege fehlen ',
        '\r\n                ',
        '\r\n            ',
        '\r\n            ',
        '\r\n        ',
        '\r\n\r\n\r\n        ',
        '\r\n        ',
        '\r\n            ',
        '\r\n                ',
        'Frage:',
        '\r\n                ',
        'Kann Mönchspfeffer bei Zyklusstörungen helfen?',
        '\r\n            ',
        '\r\n            ',
        '\r\n\r\n            ',
        '11',
        '\r\n\r\n            ',
        '\r\n                ',
        '\r\n                    ',
        'Antwort:',
        '\r\n                    ',
        '\r\n                        ',
        ' Ja,\r\n                        möglicherweise',
        '\r\n                ',
        '\r\n            ',
        '\r\n            ',
        '\r\n\r\n            ',
        '\r\n                ',
        '\r\n                    ',
        'Antwort:',
        '\r\n                    ',
        '\r\n                        ',
        ' Ja,\r\n                        wahrscheinlich',
        '\r\n                ',
        '\r\n            ',
        '\r\n             \r\n\r\n            ',
        '\r\n                ',
        '\r\n                    ',
        'Antwort:',
        '\r\n                    ',
        '\r\n                        ',
        ' Ja',
        '\r\n                ',
        '\r\n            ',
        '\r\n             \r\n\r\n\r\n            ',
        '\r\n                ',
        '\r\n                    ',
        'Antwort:',
        '\r\n                    ',
        '\r\n                        ',
        ' Ja,\r\n                        möglicherweise ein bisschen',
        '\r\n                ',
        '\r\n            ',
        '\r\n             \r\n\r\n\r\n            ',
        '\r\n                ',
        '\r\n                    ',
        'Antwort:',
        '\r\n                    ',
        '\r\n                        ',
        ' Ja,\r\n                        wahrscheinlich ein bisschen',
        '\r\n                ',
        '\r\n            ',
        '\r\n             \r\n\r\n\r\n            ',
        '\r\n                ',
        '\r\n                    ',
        'Antwort:',
        '\r\n                     ',
        '\r\n                        ',
        ' Ja, ein\r\n                        bisschen',
        '\r\n                ',
        '\r\n            ',
        '\r\n             \r\n\r\n            ',
        '\r\n                ',
        '\r\n                    ',
        'Antwort:',
        '\r\n                    ',
        '\r\n                        ',
        ' Nein,\r\n                        möglicherweise nicht',
        '\r\n                ',
        '\r\n            ',
        '\r\n             \r\n\r\n            ',
        '\r\n                ',
        '\r\n                    ',
        'Antwort: ',
        '\r\n                    ',
        ' Nein,\r\n                        wahrscheinlich nicht',
        '\r\n                ',
        '\r\n            ',
        '\r\n             \r\n\r\n            ',
        '\r\n                ',
        '\r\n                    ',
        'Antwort:',
        '\r\n                     ',
        ' Nein',
        '\r\n                ',
        '\r\n            ',
        '\r\n             \r\n\t\t\t',
        '\r\n                ',
        '\r\n                    ',
        'Antwort:',
        '\r\n                ',
        '\r\n                ',
        'Wissenschaftliche Belege fehlen ',
        '\r\n                ',
        '\r\n            ',
        '\r\n\t\t\r\n            ',
        '\r\n        ',
        '\r\n\r\n\r\n        ',
        '\r\n        ',
        '\r\n            ',
        '\r\n                ',
        'Frage:',
        '\r\n                ',
        '\r\n            ',
        '\r\n            ',
        '\r\n\r\n            ',
        '\r\n\r\n            ',
        '\r\n                ',
        '\r\n                    ',
        'Antwort:',
        '\r\n                   ',
        '\r\n                        ',
        ' Ja,\r\n                        möglicherweise',
        '\r\n                ',
        '\r\n            ',
        '\r\n            ',
        '\r\n\r\n            ',
        '\r\n                ',
        '\r\n                    ',
        'Antwort:',
        '\r\n                    ',
        '\r\n                        ',
        ' Ja,\r\n                        wahrscheinlich',
        '\r\n                ',
        '\r\n            ',
        '\r\n             \r\n\r\n            ',
        '\r\n                ',
        '\r\n                    ',
        'Antwort:',
        '\r\n                    ',
        '\r\n                        ',
        ' Ja',
        '\r\n                ',
        '\r\n            ',
        '\r\n             \r\n\r\n\r\n            ',
        '\r\n                ',
        '\r\n                    ',
        'Antwort:',
        '\r\n                     ',
        '\r\n                        ',
        ' Ja,\r\n                        möglicherweise ein bisschen',
        '\r\n                ',
        '\r\n            ',
        '\r\n             \r\n\r\n\r\n            ',
        '\r\n                ',
        '\r\n                    ',
        'Antwort:',
        '\r\n                    ',
        '\r\n                        ',
        ' Ja,\r\n                        wahrscheinlich ein bisschen',
        '\r\n                ',
        '\r\n            ',
        '\r\n             \r\n\r\n\r\n            ',
        '\r\n                ',
        '\r\n                    ',
        'Antwort:',
        '\r\n                     ',
        '\r\n                        ',
        ' Ja, ein\r\n                        bisschen',
        '\r\n                ',
        '\r\n            ',
        '\r\n             \r\n\r\n            ',
        '\r\n                ',
        '\r\n                    ',
        'Antwort:',
        '\r\n                    ',
        '\r\n                        ',
        ' Nein,\r\n                        möglicherweise nicht',
        '\r\n                ',
        '\r\n            ',
        '\r\n             \r\n\r\n            ',
        '\r\n                ',
        '\r\n                    ',
        'Antwort: ',
        '\r\n                    ',
        ' Nein,\r\n                        wahrscheinlich nicht',
        '\r\n                ',
        '\r\n            ',
        '\r\n             \r\n\r\n            ',
        '\r\n                ',
        '\r\n                    ',
        'Antwort:',
        '\r\n                     ',
        ' Nein',
        '\r\n                ',
        '\r\n            ',
        '\r\n             \r\n\t\t\t',
        '\r\n                ',
        '\r\n                    ',
        'Antwort:',
        '\r\n                    ',
        'Wissenschaftliche Belege fehlen ',
        '\r\n                ',
        '\r\n            ',
        '\r\n\r\n            ',
        '\r\n        ',
        '\r\n\t\t\t\r\n\t\t',
        '\r\n\r\n\t\t\t',
        '\r\n                ',
        'Erklärung:',
        '\r\n                ',
        'In den bisherigen Studien scheint Mönchspfeffer PMS-Beschwerden besser zu lindern als ein Scheinmedikament. Gut belegt ist das jedoch nicht, denn die Studien haben wesentliche Schwächen. Für eine Wirkung bei Zyklusstörungen gibt eine keine Belege. Aussagekräftige Studien fehlen.',
        '\r\n            ',
        '\r\n\t\t',
        '\r\n\t\t']

table3 = ['\r\n        ',
 '\r\n        ',
 '\r\n            ',
 '\r\n                ',
 'Frage: ',
 '\r\n                ',
 'Verbessert die Einnahme von Hyaluronsäure in Kapselform die Beschwerden bei einer Kniearthrose?',
 '\r\n            ',
 '\r\n            ',
 '\r\n\r\n            ',
 'wissenschafliche Beweise fehlen',
 '\r\n\r\n            ',
 '\r\n                ',
 '\r\n                    ',
 'Antwort:',
 '\r\n                    ',
 '\r\n                        ',
 ' Ja,\r\n                        möglicherweise',
 '\r\n                ',
 '\r\n            ',
 '\r\n            ',
 '\r\n\r\n            ',
 '\r\n                ',
 '\r\n                    ',
 'Antwort:',
 '\r\n                   ',
 '\r\n                        ',
 ' Ja, wahrscheinlich',
 '\r\n                    ',
 '\r\n                ',
 '\r\n            ',
 '\r\n             \r\n\r\n            ',
 '\r\n                ',
 '\r\n                    ',
 'Antwort:',
 '\r\n                    ',
 '\r\n                        ',
 ' Ja',
 '\r\n                ',
 '\r\n            ',
 '\r\n             \r\n\r\n\r\n            ',
 '\r\n                ',
 '\r\n                    ',
 'Antwort:',
 '\r\n                    ',
 '\r\n                        ',
 ' Ja, möglicherweise\r\n                        ein bisschen',
 '\r\n                ',
 '\r\n            ',
 '\r\n             \r\n\r\n\r\n            ',
 '\r\n                ',
 '\r\n                    ',
 'Antwort:',
 '\r\n                     ',
 '\r\n                        ',
 ' Ja, wahrscheinlich\r\n                        ein bisschen',
 '\r\n                ',
 '\r\n            ',
 '\r\n             \r\n\r\n\r\n            ',
 '\r\n                ',
 '\r\n                    ',
 'Antwort:',
 '\r\n                     ',
 '\r\n                        ',
 ' Ja, ein bisschen',
 '\r\n                    ',
 '\r\n                ',
 '\r\n            ',
 '         \r\n             \r\n            ',
 '\r\n                ',
 '\r\n                    ',
 'Antwort:',
 '\r\n                    ',
 '\r\n                        ',
 ' Nein,\r\n                        möglicherweise nicht',
 '\r\n                ',
 '\r\n            ',
 '\r\n             \r\n\r\n            ',
 '\r\n                ',
 '\r\n                    ',
 'Antwort: ',
 '\r\n                    ',
 ' Nein,\r\n                        wahrscheinlich nicht',
 '\r\n                ',
 '\r\n            ',
 '\r\n             \r\n\r\n            ',
 '\r\n                ',
 '\r\n                    ',
 'Antwort:',
 '\r\n                    ',
 ' Nein',
 '\r\n                ',
 '\r\n            ',
 '\r\n\r\n\t\t\t',
 '\r\n                ',
 '\r\n                    ',
 'Antwort:',
 '\r\n                    ',
 'Wissenschaftliche Belege fehlen ',
 '\r\n                ',
 '\r\n            ',
 '\r\n            ',
 '\r\n        ',
 '\r\n\r\n\r\n        ',
 '\r\n        ',
 '\r\n            ',
 '\r\n                ',
 'Frage:',
 '\r\n                ',
 '\r\n            ',
 '\r\n            ',
 '\r\n\r\n            ',
 '\r\n\r\n            ',
 '\r\n                ',
 '\r\n                    ',
 'Antwort:',
 '\r\n                    ',
 '\r\n                        ',
 ' Ja,\r\n                        möglicherweise',
 '\r\n                ',
 '\r\n            ',
 '\r\n            ',
 '\r\n\r\n            ',
 '\r\n                ',
 '\r\n                    ',
 'Antwort:',
 '\r\n                    ',
 '\r\n                        ',
 ' Ja,\r\n                        wahrscheinlich',
 '\r\n                ',
 '\r\n            ',
 '\r\n             \r\n\r\n            ',
 '\r\n                ',
 '\r\n                    ',
 'Antwort:',
 '\r\n                    ',
 '\r\n                        ',
 ' Ja',
 '\r\n                ',
 '\r\n            ',
 '\r\n             \r\n\r\n\r\n            ',
 '\r\n                ',
 '\r\n                    ',
 'Antwort:',
 '\r\n                    ',
 '\r\n                        ',
 ' Ja,\r\n                        möglicherweise ein bisschen',
 '\r\n                ',
 '\r\n            ',
 '\r\n             \r\n\r\n\r\n            ',
 '\r\n                ',
 '\r\n                    ',
 'Antwort:',
 '\r\n                    ',
 '\r\n                        ',
 ' Ja,\r\n                        wahrscheinlich ein bisschen',
 '\r\n                ',
 '\r\n            ',
 '\r\n             \r\n\r\n\r\n            ',
 '\r\n                ',
 '\r\n                    ',
 'Antwort:',
 '\r\n                     ',
 '\r\n                        ',
 ' Ja, ein\r\n                        bisschen',
 '\r\n                ',
 '\r\n            ',
 '\r\n             \r\n\r\n            ',
 '\r\n                ',
 '\r\n                    ',
 'Antwort:',
 '\r\n                    ',
 '\r\n                        ',
 ' Nein,\r\n                        möglicherweise nicht',
 '\r\n                ',
 '\r\n            ',
 '\r\n             \r\n\r\n            ',
 '\r\n                ',
 '\r\n                    ',
 'Antwort: ',
 '\r\n                    ',
 ' Nein,\r\n                        wahrscheinlich nicht',
 '\r\n                ',
 '\r\n            ',
 '\r\n             \r\n\r\n            ',
 '\r\n                ',
 '\r\n                    ',
 'Antwort:',
 '\r\n                     ',
 ' Nein',
 '\r\n                ',
 '\r\n            ',
 '\r\n             \r\n\t\t\t',
 '\r\n                ',
 '\r\n                    ',
 'Antwort:',
 '\r\n                ',
 '\r\n                ',
 'Wissenschaftliche Belege fehlen ',
 '\r\n                ',
 '\r\n            ',
 '\r\n\t\t\r\n            ',
 '\r\n        ',
 '\r\n\r\n\r\n        ',
 '\r\n        ',
 '\r\n            ',
 '\r\n                ',
 'Frage:',
 '\r\n                ',
 '\r\n            ',
 '\r\n            ',
 '\r\n\r\n            ',
 '\r\n\r\n            ',
 '\r\n                ',
 '\r\n                    ',
 'Antwort:',
 '\r\n                   ',
 '\r\n                        ',
 ' Ja,\r\n                        möglicherweise',
 '\r\n                ',
 '\r\n            ',
 '\r\n            ',
 '\r\n\r\n            ',
 '\r\n                ',
 '\r\n                    ',
 'Antwort:',
 '\r\n                    ',
 '\r\n                        ',
 ' Ja,\r\n                        wahrscheinlich',
 '\r\n                ',
 '\r\n            ',
 '\r\n             \r\n\r\n            ',
 '\r\n                ',
 '\r\n                    ',
 'Antwort:',
 '\r\n                    ',
 '\r\n                        ',
 ' Ja',
 '\r\n                ',
 '\r\n            ',
 '\r\n             \r\n\r\n\r\n            ',
 '\r\n                ',
 '\r\n                    ',
 'Antwort:',
 '\r\n                     ',
 '\r\n                        ',
 ' Ja,\r\n                        möglicherweise ein bisschen',
 '\r\n                ',
 '\r\n            ',
 '\r\n             \r\n\r\n\r\n            ',
 '\r\n                ',
 '\r\n                    ',
 'Antwort:',
 '\r\n                    ',
 '\r\n                        ',
 ' Ja,\r\n                        wahrscheinlich ein bisschen',
 '\r\n                ',
 '\r\n            ',
 '\r\n             \r\n\r\n\r\n            ',
 '\r\n                ',
 '\r\n                    ',
 'Antwort:',
 '\r\n                     ',
 '\r\n                        ',
 ' Ja, ein\r\n                        bisschen',
 '\r\n                ',
 '\r\n            ',
 '\r\n             \r\n\r\n            ',
 '\r\n                ',
 '\r\n                    ',
 'Antwort:',
 '\r\n                    ',
 '\r\n                        ',
 ' Nein,\r\n                        möglicherweise nicht',
 '\r\n                ',
 '\r\n            ',
 '\r\n             \r\n\r\n            ',
 '\r\n                ',
 '\r\n                    ',
 'Antwort: ',
 '\r\n                    ',
 ' Nein,\r\n                        wahrscheinlich nicht',
 '\r\n                ',
 '\r\n            ',
 '\r\n             \r\n\r\n            ',
 '\r\n                ',
 '\r\n                    ',
 'Antwort:',
 '\r\n                     ',
 ' Nein',
 '\r\n                ',
 '\r\n            ',
 '\r\n             \r\n\t\t\t',
 '\r\n                ',
 '\r\n                    ',
 'Antwort:',
 '\r\n                    ',
 'Wissenschaftliche Belege fehlen ',
 '\r\n                ',
 '\r\n            ',
 '\r\n\r\n            ',
 '\r\n        ',
 '\r\n\t\t\t\r\n\t\t',
 '\r\n\r\n\t\t\t',
 '\r\n                ',
 'Erklärung:',
 '\r\n                ',
 'Die Frage wurde in drei kleinen Studien mit diversen Mängeln untersucht. Sie kommen zu widersprüchlichen Ergebnissen. Daher können wir nicht sicher sagen, ob Hyaluronsäure zum Einnehmen einen günstigen Einfluss auf die Beschwerden bei einer Kniearthrose hat. Auch über mögliche Risiken können wir auf Basis der besten verfügbaren Studien keine verlässlichen Aussagen treffen.',
 '\r\n            ',
 '\r\n\t\t',
 '\r\n\t\t']

table4 = ['\n',
 '\n',
 '\n',
 'Zeitungsartikel: ',
 '\n',
 'Kopfschmerzen: Es ist eine Reizverarbeitungsstörung',
 ' (Der Standard, 5. 6. 2011)',
 '\n',
 '\n',
 '\n',
 'Frage:',
 '\n',
 'Können rezeptfreie Kombinationspräparate bei Spannungskopfschmerz und Migräne besser helfen als Medikamente, die nur Einzelwirkstoffe beinhalten?',
 '\n',
 '\n',
 '\n',
 'Antwort:',
 '\n',
 'Der Zusatz von Koffein kann bei einigen Menschen die Wirkung gängiger Schmerzmittel geringfügig verstärken. Möglicherweise istdie Kombination von Acetylsalicylsäure (ASS), Paracetamol und Koffein als am besten wirksam. Dabei konnte aber keine bessere Verträglichkeit der Kombinationspräparate festgestellt werden. Für mehrere andere Wirkstoffe bzw. Wirkstoffkombinationen gibt es jedoch noch keine Vergleichsdaten.',
 '\n',
 '\n',
 '\n',
 'Beweislage:',
 '\n',
 '\n',
 '\n',
 '\n',
 '\n',
 '\n',
 'Mittlere',
 ' wissenschaftliche Beweislage',
 '\n',
 'für die geringfügige Überlegenheit von Koffein als Zusatz zu gängigen Schmerzmitteln',
 '\n',
 '\n',
 '\n',
 'Beweislage:',
 '\n',
 '\n',
 '\n',
 '\n',
 '\n',
 '\n',
 'Niedrige',
 ' wissenschaftliche Beweislage',
 '\n',
 'für die Überlegenheit der Kombination von ASS, Paracetamol und Koffein im Vergleich zu den Einzelpräparaten',
 '\n',
 '\n',
 '\n']


text = ['Zur Wirksamkeit von Magnesiumsalzen bei ',
                  'anstrengungsbedingten Muskelkrämpfen, etwa bei Sportlern, ',
                  'finden sich keine qualitativ hochwertigen Studien. Bei ',
                  'Krämpfen der Beinmuskeln ohne erkennbare Ursache haben ',
                  'Forscher in Studien keinen Effekt von Magnesium nachweisen ',
                  'können, der über Placebo hinausgeht. Schwangere Frauen ',
                  'profitieren möglicherweise von Magnesiumpräparaten, ',
                  'allerdings sind diese Belege nicht sehr belastbar.']

print(process_table3(table5))